### PR TITLE
add code based login

### PR DESCRIPTION
**Pull request by vanous**
perhaps let's move the conversation here, for now...

### CODE REVIEW

**Comment by micw** [comment]
This is the request from my device's recordings:
```
POST https://account.huami.com/v2/client/login

URLEncoded form                                                                                                                                                                       app_name:           com.xiaomi.hm.health
country_code:       DE
code:               ALSG_CLOUDSRV_******
device_id:          02:00:00:00:00:00
device_model:       android_phone
app_version:        4.0.9
grant_type:         request_token
allow_registration: false
dn:                 account.huami.com,api-user.huami.com,api-watch.huami.com,api-analytics.huami.com,app-analytics.huami.com,api-mifit.huami.com
third_name:         xiaomi-hm-mifit
source:             com.xiaomi.hm.health:4.0.9:8046
lang:               de

```

**Comment by micw** [comment]
I think I should completely refactor the code and separate the auth_code retrieval from the actual data retrieval. But I'd first see how the device/app keeps the auth_code alive.

**Comment by vanous** [comment]
Hmm, still no luck.

{'allow_registration': 'false',
 'app_version': '4.0.9',
 'code': 'ALSG_CLOUDSRV_****',
 'country_code': 'DE',
 'device_id': '02:00:00:00:00:00',
 'device_model': 'android_phone',
 'dn': 'account.huami.com,api-user.huami.com,api-watch.huami.com,api-analytics.huami.com,app-analytics.huami.com,api-mifit.huami.com',
 'grant_type': 'request_token',
 'lang': 'de',
 'source': 'com.xiaomi.hm.health:4.0.9:8046',
 'third_name': 'xiaomi-hm-mifit'}

{'error_code': '0100'}

does this (branch) work for you?

**Comment by micw** [comment]
did you replace the "code"? I had no time to test it  yet.

**Comment by vanous** [comment]
😃😃😃 of course .

**Comment by vanous** [comment]
It is actually an argument .

**Comment by micw** [comment]
Hm, I get an error 0109...
I will remove the account from the app and sniff the traffic again later today.

**Comment by vanous** [comment]
Same here...

**Comment by micw** [comment]
Wow, that was hard to figure out: I have re-done everything, wiped mifit settings from my device, re-authenticated, sniffed the traffic. Then I wrote a new script that posts _exactly_ the same request as the device (including headers). Result: code 0106.
Then I went through the flow to see whats the difference. Actually its that the app does never follow the redirect to https://api-mifit-cn.huami.com/huami.health.loginview.do?code=... while the browser does. This call "uses" and therefore invalidated the one-time code.

So error_code 0106 obviously means that the code is not valid (anymore).

The solution is simple: stop the browser from calling the redirect URL (hard) or alter the redirect url so that the code does not get invalidated (easy).

It's not possible to alter the domain part since it's fixed in the oauth process. But you can alter the very end of the path part. So starting the login procedure at the modified URL:

https://account.xiaomi.com/oauth2/authorize?skip_confirm=false&client_id=428135909242707968&pt=1&scope=1+6000+16001+20000&redirect_uri=https%3A%2F%2Fapi-mifit-cn.huami.com%2Fhuami.health.loginview.do_not&_locale=de_DE&response_type=code

Leads to an unused and valid code :-)

I have created mifit_code_to_apptoken.py that contains this particular login method.

**Comment by vanous** [comment]
Wow, this is great! I am trying right now :)

**Comment by vanous** [comment]
Perfect, this is working! Good trick with the redirect url. 
Step data can be without 'stage', i am digging through now :)

`{'ttl': 14, 'dis': 9, 'cal': 1, 'wk': 1, 'rn': 0, 'runDist': 0, 'runCal': 1}`

**Comment by vanous** [comment]
My latest commit is fixing some activity types. I can confirm that: sleep is OK (light/deep), and also activities are now correct (see modifications, based on my records from two days ago). These are 100% correct if compared to the official stage decoding.

**Comment by micw** [comment]
Could you please separate your PRs? I'd like to merge the last commit but not the login code modifications (because I'll rewrite the login code and separate it from data gathering)

**Comment by micw** [comment]
> Perfect, this is working! Good trick with the redirect url.
> Step data can be without 'stage', i am digging through now :)
> 
> `{'ttl': 14, 'dis': 9, 'cal': 1, 'wk': 1, 'rn': 0, 'runDist': 0, 'runCal': 1}`

The "stage" contains more detailed data (per time range or per activity). I plan to write some "sync to google fit" thing, so I'll need the details

**Comment by vanous** [comment]
sure, you can delete this one

**Comment by vanous** [comment]
btw, i think there is probably more then https://api-mifit.huami.com/v1/data/band_data.json ... device data etc... because when you log on different phone, it knows your devices...

**Comment by micw** [comment]
There's lot more, It's pulling the devices (knowing their bluetooth id and for mi band 4 also the secret key). It's also somewhere downloading the heart rate data.
I can figure out the endpoints if you'd like to investigate in it.

**Comment by vanous** [comment]
for me, there is no use of that... it might be interesting to other people though...

**Comment by oeph** [comment]
For anyone interested in exact the oauth calls, you can find more information here https://xiaomi-passport.github.io/authorization-code.html

**Comment by vanous** [comment]
well, there is now also the https://github.com/argrento/huami-token which does similar thing

**Pull request closed without merging**
